config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  devise_for :users

  resources :posts, only: [:index, :show], format: false do
    # Ugnjezdio sam ti tags rutu da ruta bude ljepša /posts/tags a ne samo /tags
    # Nije greška samo da vidiš kako se to radi
    collection do
      get 'tags/:tag', to: 'posts#index', as: :tag
    end
  end

  namespace :user do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy

  validates :title, presence: true
  mount_uploader :image, ImageUploader
  # Pretvorio sam ti metodu klase u scope jer tako je možeš vezati, naprimjer:
  # Post.search('term').tagged_with('tag')...
  scope :tagged_with, ->(id){ joins(taggings: [:tag]).where(tags: { id: id }) }

  #def self.tagged_with(id)
  # #Tag.find_by_name!(name).posts
  # Tag.find_by_id!(id).posts
  #end

  def tag_list
    tags.join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(", ").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :posts, through: :taggings, dependent: :destroy

    def to_s
        name
    end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name    
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show
  helper_method :sort_column, :sort_direction

  # GET /posts
  # Malo sam ti refaktorirao ovo, imat ćeš kasnije i search postova pa će ti biti preglednije/jednostavnije
  def index
    # Dodao sam includes jer na indexu imaš ispis tagova i N+1 query koji uvijek treba izbjegavati
    # Prije - https://d.pr/i/asTdxZ
    # Poslije - https://d.pr/i/E8i8vm
    @posts = Post.includes(:tags, :user).order("#{sort_column} #{sort_direction}")
    @posts = @posts.tagged_with(params[:tag]) if params[:tag]
    @posts = @posts.page(params[:page])
  end

  # GET /posts/1
  def show
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def sort_column
      Post.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/user/posts_controller.rb
class User::PostsController < User::BaseController
  before_action :set_post, only: %i[ show edit update destroy ]
  helper_method :sort_column, :sort_direction

  # GET /posts
  # Malo sam ti refaktorirao ovo, imat ćeš kasnije i search postova pa će ti biti preglednije/jednostavnije
  def index
    # Dodao sam includes jer na indexu imaš ispis tagova i N+1 query koji uvijek treba izbjegavati
    # Prije - https://d.pr/i/asTdxZ
    # Poslije - https://d.pr/i/E8i8vm
    @posts = current_user.posts.includes(:tags).order("#{sort_column} #{sort_direction}")
    @posts = @posts.tagged_with(params[:tag]) if params[:tag]
    @posts = @posts.page(params[:page])
  end

  # GET /user/posts/1
  def show
  end

  # GET /user/posts/new
  def new
    @post = Post.new
  end

  # GET /user/posts/1/edit
  def edit
  end

  # POST /user/posts
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to [:user, @post], notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /user/posts/1
  def update
    if @post.update(post_params)
      redirect_to [:user, @post], notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /user/posts/1
  def destroy
    @post.destroy

    redirect_to user_posts_url, notice: "Post was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      # Dodao sam ti :image_cache parametar tu i u formu. Primjetiti ćeš da ako propadne forma zbog validacije a učitao si sliku da je
      # moraš nanovo učitati, :image_cache ti je "pamti". Da ti se field zove file, cache atribut bi bio file_cache
      params.require(:post).permit(:title, :text, :image, :image_cache, :tag_list)
    end

    def sort_column
      Post.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, sort: column, direction: direction
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_login_logout.html.erb
<div id="container">
    <div id="user_nav">
        <%= link_to 'Home', posts_path %> |
        <% if user_signed_in? %>
            <strong>
                <%= sanitize link_to current_user.full_name, user_posts_path %> |
            </strong>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path %> |
            <%= link_to 'Login', new_user_session_path %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/login_logout' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Text</th>
      <th>Image</th>
      <th>Tags</th>
      <th>Writer</th>
      <th><%= sortable "created_at" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= sanitize post.text %></td>
        <td><%= image_tag post.image_url, width: 80 if post.image.presence %></td>
        <td><%= sanitize post.tags.map { |t| link_to t, tag_posts_path(t) }.join(', ') %></td>
        <td><%= post.user.full_name %></td>
        <td><%= post.created_at.strftime("%d-%m-%Y %R") %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @posts %>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Post', new_user_post_path %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @post.id %>
</p>

<p>
  <strong>Writer: </strong>
  <%= @post.user.full_name if @post.user.presence %>
<p>

<p>
  <strong>Tags:</strong>
  <%= @post.tag_list %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= sanitize @post.text %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@post.image, style: "max-height: 50vw") %>
</p>

<%= link_to 'Back', posts_path %>

app/views/user/posts/_form.html.erb
<%= form_with(model: [:user, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list, id: :tag_list %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <% if @post.image != nil %>
      <%= form.label :current_image %>
      <%= image_tag(@post.image, style: "max-height: 50vw") %>
      <br>
    <% end %>
    <%= form.hidden_field :image_cache %>
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :post_text, class: :tinymce %>
    <%= tinymce %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', user_posts_path %>

app/views/user/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profile</h1>
<p><b>Id:</b> <%= current_user.id %></p>
<p><b>Full name</b>: <%= current_user.full_name %></p>
<p><b>Email:</b> <%= current_user.email %></p>
<p><b>Bio:</b> <%= current_user.bio %></p>

<%= link_to 'Edit profile', edit_user_registration_path %>

<hr>

<h1>My Posts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Text</th>
      <th>Image</th>
      <th>Tags</th>
      <th>Writer</th>
      <th><%= sortable "created_at" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= sanitize post.text %></td>
        <td><%= image_tag post.image_url, width: 80 if post.image.presence %></td>
        <td><%= sanitize post.tags.map { |t| link_to t, tag_posts_path(t) }.join(', ') %></td>
        <td><%= post.user.full_name if post.user.presence %></td>
        <td><%= post.created_at.strftime("%d-%m-%Y %R") %></td>
        <td><%= link_to 'Show', user_post_path(post) %></td>
        <td><%= link_to 'Edit', edit_user_post_path(post) %></td>
        <td><%= link_to 'Destroy', user_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @posts %>

<br>

<%= link_to 'New Post', new_user_post_path %>

app/views/user/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path %>

app/views/user/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @post.id %>
</p>

<p>
  <strong>Writer: </strong>
  <%= @post.user.full_name if @post.user.presence %>
<p>

<p>
  <strong>Tags:</strong>
  <%= @post.tag_list %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= sanitize @post.text %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@post.image, style: "max-height: 50vw") %>
</p>

<%= link_to 'Edit', edit_user_post_path(@post) %> |
<%= link_to 'Back', user_posts_path %>